config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :goals do
    member do
      patch :complete
  end
end
  root 'goals#index'
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
    belongs_to :user
    
    def completed?
        !completed_at.blank?
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :find_goal, only:[:show, :edit, :update, :destroy]
    
    def index
        if user_signed_in?
			# Selects the items where the user's id is the same as the current_user.
			# Selects only the checklist items for the current_user.
			@goals = Goal.where(:user_id => current_user.id).order("created_at DESC")
		end	
    end
    def show
    end
    
    def new
        @goal  = current_user.goals.build
        
    end
    
    def create
        @goal = current_user.goals.build(goal_params)
        if @goal.save
            redirect_to root_path
        end
    end
    
    
    def edit
    end
    def update
        if @goal.update(goal_params)
            redirect_to goal_path(@goal)
        else
            render 'edit'
        end
    end
    def destroy
        @goal.destroy
        redirect_to root_path
    end
    
    def complete
        
        @goal = Goal.find(params[:id])
        @goal.update_attribute(:completed_at, Time.now)
        redirect_to root_path
    end
    
    private 
    
    def goal_params
        params.require(:goal).permit(:title, :description)
    end
        
    def find_goal
        @goal = Goal.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for @goal do |f| %>
  <%=f.input :title, label: "Goal" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Checklist</h1>
<%= render 'form' %>

app/views/goals/index.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->
<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @goals.each do |goal| %>
			<div class="index-wrapper">
				<% if goal.completed? %>
					<div class="row item">
						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="goal-title"><strike><%= link_to goal.title, goal %></strike></h2>
							<p style="opacity: 0.5;" class="goal-sub-title goal-desc"><%= goal.description %></p>
							<p style="opacity: 0.5;" class="time-created-at goal-sub-title">Completed <%= time_ago_in_words(goal.completed_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_goal_path(goal), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to goal, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>	
					</div>
				<% else %>	
					<div class="row goal">
						<div class="col-md-8">
							<h2 class="goal-title"><%= goal.title %></h2>
							<p class="item-sub-title goal-desc"><%= goal.description %></p>
							<p style="opacity: 0.5;" class="time-created-at goal-sub-title">Created <%= time_ago_in_words(goal.created_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_goal_path(goal), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to goal, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

		<% end %>	
	</div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/goals/new.html.erb
<%= render 'form' %>

app/views/goals/show.html.erb
<h2> <%=@goal.title %></h2>
<p> <%=@goal.description %></p>

<%= link_to "back", root_path %>
<%= link_to "edit", edit_goal_path(@goal) %>

app/views/layouts/_static_landing_page.html.erb
<div class = "jumbotron">
    <h1>Welcome to Goals Twitter</h1>
    <p> find a buddy to keep up with your goals</p>
    <%= link_to "sign up", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "log in", new_user_session_path, class: "btn btn-success" %>
    
    
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  
  <nav class = "navbar navbar-default">
    <div class = "container">
      <div class = "navbar-header">
        <%= link_to "checklist", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "signup", new_user_registration_path %></li>
          <% if current_user.present? %>
          <li><%=link_to "signout" , destroy_user_session_path, method: :delete %></li>
          <% else%>
          <li><%= link_to "kennyloggins", new_user_session_path %></li>
          <%end%>
        </ul>
        <% if user_signed_in? %>
        <%=link_to "new goal", new_goal_path, class: "navbar-text navbar-link 
        navbar-right" %>
        <%end%>
      </div>
    
  </nav>
  
  
  <p class ="notice"><%= notice %></p>
  <p class ="alert"><%= alert %></p>

<%= yield %>

</body>
</html>